// stores/counter.js
import { defineStore } from 'pinia'

export const useResourcesStore = defineStore('resourcesStore', {
  state: () => {
    return { info: [
      {
        "key": "KoMuX",
        "nameShort": "KoMuX",
        "nameLong": "Kompositamuster-Explorer",
        "description": 'Im <strong>Kompositamuster-Explorer</strong> kann man sich Listen mit <u>Frequenzen</u> und nach unterschiedlichen linguistischen Kriterien zusammengestellte Gruppen von mehr als 50.000 Komposita anzeigen lassen, die vorher automatisch annotiert, d.h. mit Merkmalen<br/>(<a href="https://www.bubenhofer.com/korpuslinguistik/kurs/index.php?id=linginformationen.html">Annotation</a>) versehen wurden.',
        "img": "/img/sources/komux.jpg",
        "url": "https://www.owid.de/plus/komux/",
        "tags": ["Annotation", "Suche", "Explorativ", "Datenbank", "Frequenz",  "Kategorie"],
        "quest": "https://www.owid.de/plus/komux/?lem={q}",
        "search_display": "Netz",
        "search_type":"Datenbank",
        "search_subtype":"Explorativ",
        "search_functions": ["Suchanfrage", "KWIC", "Frequenz", "Muster"],
        "search_patterns": ["E-Muster", "Z-Muster", "D-Muster"],
        "search_parts": ["Verb", "Nomen", "Adjektiv"],
      },
      {
        "key": "PREPCON",
        "nameShort": "PREPCON<sup>online</sup>",
        "nameLong": "Präposition-Nomen-Verbindungen im Kontext",
        "description": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque recusandae dolorem quae eum ipsum sapiente itaque officia reiciendis enim et voluptate sunt, veritatis provident assumenda pariatur autem quia! Pariatur.',
        "img": "/img/sources/prepcon.jpg",
        "url": "http://uwv.ids-mannheim.de/prepcon/prepcon_online.html",
        "tags": ["Vollautomatisch", "Frequenz", "KWIC", "EMuster"],
        "search_display": "Netz",
        "search_type":"Datenbank",
        "search_subtype":"Explorativ",
        "search_functions": ["Suchanfrage", "KWIC", "Frequenz", "Muster", "Beleg"],
        "search_patterns": ["E-Muster", "Z-Muster", "D-Muster"],
        "search_parts": ["Verb", "Nomen", "Präposition", "Adjektiv", "Adverb", "Phrasem", "Satz"],
      },
      {
        "key": "PREPCON_ex",
        "nameShort": "PREPCON<sup>explorativ</sup>",
        "nameLong": "Präposition-Nomen-Verbindungen im Kontext",
        "description": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque recusandae dolorem quae eum ipsum sapiente itaque officia reiciendis enim et voluptate sunt, veritatis provident assumenda pariatur autem quia! Pariatur.',
        "img": "/img/sources/prepcon_explorativ.jpg",
        "url": "http://uwv.ids-mannheim.de/prepcon/prepcon_online.html",
        "tags": ["Suche", "Explorativ", "Datenbank", "Frequenz", "KWIC", "Präposition", "Nomen", "EMuster"],
        "quest": "http://uwv.ids-mannheim.de/prepcon/modul1/tables.html?{q}",
        "search_display": "Suche",
        "search_type":"Datenbank",
        "search_subtype":"Explorativ",
        "search_functions": ["Suchanfrage", "KWIC", "Frequenz", "Muster", "Basiselement"],
        "search_patterns": ["Z-Muster", "D-Muster"],
        "search_parts": ["Verb", "Nomen", "Präposition", "Phrasem"],
      },
      {
        "key": "PREPCON_temp",
        "nameShort": "PREPCON<sup>temporal</sup>",
        "nameLong": "PREPCON temporal-Kurzartikel",
        "description": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque recusandae dolorem quae eum ipsum sapiente itaque officia reiciendis enim et voluptate sunt, veritatis provident assumenda pariatur autem quia! Pariatur.',
        "img": "/img/sources/prepcon_temporal.jpg",
        "url": "http://uwv.ids-mannheim.de/prepcon/prepcon_online.html",
        "tags": ["Vollautomatisch", "Frequenz", "KWIC", "EMuster"],
        "quest": "http://uwv.ids-mannheim.de/prepcon/modul2/inventar/{q}",
        "search_display": "Stichwortliste",
        "search_type":"Inventar",
        "search_subtype":"Deskriptiv",
        "search_functions": ["Suchanfrage", "KWIC", "Frequenz", "Muster", "Narrativer Text", "Satellitenfeld"],
        "search_patterns": ["E-Muster", "D-Muster"],
        "search_parts": ["Verb", "Nomen", "Präposition", "Adjektiv", "Adverb"],
      },
      {
        "key": "PREPCON_kon",
        "nameShort": "PREPCON<sup>kontrastiv</sup>",
        "nameLong": "PREPCON kontrastiv",
        "description": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque recusandae dolorem quae eum ipsum sapiente itaque officia reiciendis enim et voluptate sunt, veritatis provident assumenda pariatur autem quia! Pariatur.',
        "img": "/img/sources/prepcon_kontrastiv.jpg",
        "url": "http://uwv.ids-mannheim.de/prepcon/modul3/index.html",
        "tags": ["Vollautomatisch", "Frequenz", "KWIC", "EMuster"],
        "quest": "http://uwv.ids-mannheim.de/prepcon/modul3/quantitativ/{q}.html",
        "search_display": "Suche",
        "search_type":"Korpuszentriertes Format",
        "search_subtype":"Kontrastiv",        
        "search_functions": ["Suchanfrage", "KWIC", "Frequenz", "Muster", "Annotation"],
        "search_patterns": ["E-Muster", "Z-Muster"],
        "search_parts": ["Verb", "Nomen", "Präposition", "Adjektiv", "Adverb", "Phrasem", "Satz"],
      },
      {
        "key": "MAP",
        "nameShort": "MAP",
        "nameLong": "Musterbank Argumentmarkierender Präpositionen",
        "description": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque recusandae dolorem quae eum ipsum sapiente itaque officia reiciendis enim et voluptate sunt, veritatis provident assumenda pariatur autem quia! Pariatur.',
        "img": "/img/sources/map.jpg",
        "url": "",
        "tags": ["Deskriptiv", "Muster", "Präpositionen", "Visualisierung"],
        "search_display": "Netz",
        "search_type": "Online-Wörterbuch",
        "search_subtype": "Semi-Automatisch",
        "search_functions": ["Suchanfrage", "KWIC", "Frequenz", "Muster", "Annotation"],
        "search_patterns": ["E-Muster"],
        "search_parts": ["Verb", "Präposition", "Adverb", "Phrasem", "Satz"],
      },
      {
        "key": "Redeeinleiter",
        "nameShort": "Wörterbuch Redeeinleiter",
        "nameLong": "Kleines Wörterbuch der Redeeinleiter",
        "description": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque recusandae dolorem quae eum ipsum sapiente itaque officia reiciendis enim et voluptate sunt, veritatis provident assumenda pariatur autem quia! Pariatur.',
        "img": "/img/sources/redeeinleiter.jpg",
        "url": "https://www.owid.de/plus/redeeinleiter",
        "tags": ["Deskriptiv", "Redeeinleiter"],
        "search_display": "Stichwortliste",
        "search_type": "Online-Wörterbuch",
        "search_subtype": "Händisch / Qualitativ",
        "search_functions": ["Lückenfüller", "Satellitenfeld"],
        "search_patterns": ["D-Muster"],
        "search_parts": ["Verb", "Präposition", "Phrasem", "Satz"],
      },
      {
        "key": "SpruchList",
        "nameShort": "SpruchList",
        "nameLong": "Referenzinventar deutscher Sprichwörter und Sprüche",
        "description": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque recusandae dolorem quae eum ipsum sapiente itaque officia reiciendis enim et voluptate sunt, veritatis provident assumenda pariatur autem quia! Pariatur.',
        "img": "/img/sources/spruchlist.jpg",
        "url": "http://uwv.ids-mannheim.de/spruchlist/",
        "tags": ["Liste", "Mehrworteinheiten", "Sprichwörter"],
        "search_display": "Stichwortliste",
        "search_type": "Studie",
        "search_subtype": "Deskriptiv",
        "search_functions": ["Suchanfrage", "Muster"],
        "search_patterns": ["Z-Muster"],
        "search_parts": ["Phrasem", "Satz"],
      },
      {
        "key": "DTWW",
        "nameShort": "DTWW",
        "nameLong": "Deutsch-türkische Wortverbindungen Wirtschaft",
        "description": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque recusandae dolorem quae eum ipsum sapiente itaque officia reiciendis enim et voluptate sunt, veritatis provident assumenda pariatur autem quia! Pariatur.',
        "img": "/img/sources/dtww.jpg",
        "url": "http://wvonline.ids-mannheim.de/dtww/dtww_komplett.htm",
        "tags": ["Liste", "Mehrworteinheiten", "Sprichwörter", "Mehrsprachig", "Zweisprachig"],
        "search_display": "Stichwortliste",
        "search_type": "Korpuszentriertes Format",
        "search_functions": ["Suchanfrage", "KWIC", "Muster"],
        "search_patterns": ["E-Muster", "Z-Muster", "D-Muster"],
        "search_parts": ["Verb", "Nomen", "Präposition", "Adjektiv", "Adverb", "Phrasem", "Satz"],
      },
      {
        "key": "SPRW",
        "nameShort": "Sprichwörterbuch",
        "nameLong": "Sprichwörterbuch",
        "description": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque recusandae dolorem quae eum ipsum sapiente itaque officia reiciendis enim et voluptate sunt, veritatis provident assumenda pariatur autem quia! Pariatur.',
        "img": "/img/sources/sprichwoerterbuch.jpg",
        "url": "https://www.owid.de/wb/sprw/start.html",
        "tags": ["Liste", "Mehrworteinheiten", "Sprichwörter"],
        "quest": "https://www.owid.de/artikel/{q}",
        "search_display": "Stichwortliste",
        "search_type": "Online-Wörterbuch",
        "search_subtype": "Deskriptiv",
        "search_functions": ["Suchanfrage", "KWIC", "Beleg", "Muster"],
        "search_patterns": ["E-Muster", "Z-Muster", "D-Muster"],
        "search_parts": ["Verb", "Nomen", "Präposition", "Adjektiv", "Adverb", "Phrasem", "Satz"],
      },
      {
        "key": "Verlaufsformen",
        "nameShort": "Verlaufsformen im Deutschen",
        "nameLong": "Kleines Wörterbuch der Verlaufsformen im Deutschen",
        "description": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque recusandae dolorem quae eum ipsum sapiente itaque officia reiciendis enim et voluptate sunt, veritatis provident assumenda pariatur autem quia! Pariatur.',
        "img": "/img/sources/verlaufsformen.jpg",
        "url": "https://www.owid.de/service/stichwortlisten/progdb",
        "tags": ["Wörterbuch", "Mehrworteinheiten", "Verlaufsformen"],
        "quest": "https://www.owid.de/artikel/{q}",
        "search_display": "Suche",
        "search_type": "Online-Wörterbuch",
        "search_subtype": "Kontrastiv",
        "search_functions": ["Suchanfrage", "KWIC", "Annotation", "Muster"],
        "search_patterns": ["E-Muster", "Z-Muster", "D-Muster"],
        "search_parts": ["Verb", "Nomen", "Präposition", "Adjektiv", "Adverb", "Phrasem", "Satz"],
      },
      {
        "key": "WVBF",
        "nameShort": "Wortverbindungsfelder",
        "nameLong": "zu Präpositon+Grund-Netz",
        "description": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque recusandae dolorem quae eum ipsum sapiente itaque officia reiciendis enim et voluptate sunt, veritatis provident assumenda pariatur autem quia! Pariatur.',
        "img": "/img/sources/wortverbindungsfelder.jpg",
        "url": "http://wvonline.ids-mannheim.de/wvfelder-v3/grund-graphik.html",
        "tags": ["Wörterbuch", "Mehrworteinheiten", "Verlaufsformen", "Wortbildungsmuster"],
        "search_display": "Netz",
        "search_type": "Studie",
        "search_subtype": "Semi-Automatisch",
        "search_functions": ["Suchanfrage", "KWIC", "Frequenz", "Muster"],
        "search_patterns": ["E-Muster", "Z-Muster", "D-Muster"],
        "search_parts": ["Verb", "Nomen", "Präposition", "Adjektiv", "Adverb", "Phrasem", "Satz"],
      },
      {

        "key": "DRI",
        "nameShort": "Deutsch-russische Idiome online",
        "nameLong": "Auszug aus 'Moderne deutsch-russische Idiomatik: Ein Korpuswörterbuch",
        "description": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque recusandae dolorem quae eum ipsum sapiente itaque officia reiciendis enim et voluptate sunt, veritatis provident assumenda pariatur autem quia! Pariatur.',
        "img": "/img/sources/dri.jpg",
        "url": "http://wvonline.ids-mannheim.de/idiome_russ/AKTE_zu_den_Akten_legen.htm",
        "tags": ["Liste", "Mehrworteinheiten", "Sprichwörter", "Mehrsprachig", "Zweisprachig"],
        "search_display": "Netz",
        "search_type": "Studie",
        "search_subtype": "Händisch / Qualitativ",
        "search_functions": ["Suchanfrage", "KWIC", "Frequenz", "Muster"],
        "search_patterns": ["E-Muster", "Z-Muster", "D-Muster"],
        "search_parts": ["Verb", "Nomen", "Präposition", "Adjektiv", "Adverb", "Phrasem", "Satz"],
      },
      {

        "key": "PhrasKomp",
        "nameShort": "Phrasenkomposita des Deutschen",
        "nameLong": "Inventar von Phrasenkomposita des Deutschen",
        "description": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Alias eaque recusandae dolorem quae eum ipsum sapiente itaque officia reiciendis enim et voluptate sunt, veritatis provident assumenda pariatur autem quia! Pariatur.',
        "img": "/img/sources/wortverbindungsfelder.jpg",
        "url": "",
        "tags": ["Umfrage", "Statistik", "Benutzungsstudie"],
        "search_display": "Netz",
        "search_type": "Studie",
        "search_subtype": "Semi-Automatisch",
        "search_functions": ["Suchanfrage", "KWIC", "Frequenz", "Muster"],
        "search_patterns": ["E-Muster", "Z-Muster", "D-Muster"],
        "search_parts": ["Verb", "Nomen", "Präposition", "Adjektiv", "Adverb", "Phrasem", "Satz"],
      },
    
    ] }
  },
  // could also be defined as
  // state: () => ({ count: 0 })
  actions: {
    increment() {
      this.count++
    },
    getResources: function (filter) {
      if(filter == undefined || filter == null || filter.length === 0) return this.info;
      return this.info.filter(resource => filter.includes(resource.key))
    }
  },

  getters: {
    uniqueCategories: function (state) {
      return [...new Set(state.info.map((resource) => resource.categories).flat())]
    },    
  },
})